version: "3"
services:
    web:
        # image: u1and0/locate-server:latest
        build:
            context: .
        ports:
          - 8081:8080
        volumes:
            - db:/var/lib/mlocate
        environment:
            - TZ=Asia/Tokyo
        working_dir: /var/www
        entrypoint: /usr/bin/locate-server
        # command: ["-debug"]

    db:
        image: busybox
        volumes:
            - /var/lib/mlocate:/var/lib/mlocate

    app:
        build:
             context: ./app
        volumes:
            - db:/var/lib/mlocate
      ## app関連その他ディレクトリ
      # personal:
      #     build:
      #         context: ./app
      # common:
      #     build:
      #         context: ./app
      # communication:
      #     build:
      #         context: ./app

      ## バックアップ　監視関連
      #     backup:
      #         build:
      #             context: ./backup

    # stalker: # locate-serverのログ監視
    #     image: busybox:latest
    #     volumes:
    #         - db:/var/lib/mlocate
    #     command: [tail, -f, /var/lib/mlocate/locate.log]
    #
    # observer:
    #     build:
    #          context: ./app
    #     environment:
    #         - TZ=Asia/Tokyo
    #     volumes:
    #         - db:/var/lib/mlocate
    #     command: [watch, -n10, ls, -ltrAh, /var/lib/mlocate]

volumes:
    db:
