version: "3"
services:
    web:
        build:
            context: .
        ports:
            - 8082:8080
        depends_on:
            - db
        volumes:
            - db:/var/lib/mlocate
            - /home/u1and0:/home/u1and0
        environment:
            - TZ=Asia/Tokyo
            # - LOCATE_PATH=/var/lib/mlocate/mlocate.db
        entrypoint: /usr/bin/locate-server
        # command: [-s, -r, \\gr.jp\DFS]

    db:
        image: busybox
        volumes:
            # - /ShareUsers:/ShareUsers
            - /var/lib/mlocate:/var/lib/mlocate
              # - /home/u1and0:/home/u1and0

    app:
        build:
             context: ./app
        depends_on:
            - db
        volumes:
            - db:/var/lib/mlocate
            - /home/u1and0:/home/u1and0
        environment:
            - UPDATEDB_PATH=/home/u1and0
            - OUTPUT=mlocate.db
      ## app関連その他ディレクトリ
      # personal:
      #     build:
      #         context: ./app
      # common:
      #     build:
      #         context: ./app
      # communication:
      #     build:
      #         context: ./app

      ## バックアップ　監視関連
      #     backup:
      #         build:
      #             context: ./backup
      #
    stalker: # locate-serverのログ監視
        image: busybox:latest
        volumes:
            - db:/var/lib/mlocate
        command: [tail, -f, /var/lib/mlocate/locate.log]

    observer:
        build:
             context: ./app
        environment:
            - TZ=Asia/Tokyo
        volumes:
            - db:/var/lib/mlocate
        command: [watch, -n10, ls, -ltrAh, /var/lib/mlocate]

volumes:
    db:
